basePath: /gr
host: localhost
info:
  contact: {}
  description: Rokwire Groups Building Block API Documentation.
  license: {}
  title: Rokwire Groups Building Block API
  version: 1.0.2
paths:
  /api/group-categories:
    get:
      consumes:
      - application/json
      description: Gives all group categories.
      operationId: GetGroupCategories
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      security:
      - APIKeyAuth: []
  /version:
    get:
      description: Gives the service version.
      operationId: Version
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
schemes:
- https
securityDefinitions:
  APIKeyAuth:
    in: header
    name: ROKWIRE-API-KEY
    type: apiKey
swagger: "2.0"
